# Generated by Django 4.2.24 on 2025-09-04 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=255)),
                ('billed_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Denied', 'Denied'), ('Under Review', 'Under Review')], max_length=50)),
                ('insurer_name', models.CharField(max_length=255)),
                ('discharge_date', models.DateField()),
                ('burger_combo_code', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='claims.claim')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpt_codes', models.CharField(max_length=255)),
                ('denial_reason', models.TextField(blank=True, null=True)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='claims.claim')),
            ],
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(default='Flagged for review', max_length=255)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='claims.claim')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('claim', 'user')},
            },
        ),
    ]
