# Generated by Django 4.2.24 on 2025-09-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimdetail',
            name='denial_reason',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(max_length=5000),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['patient_name'], name='claims_clai_patient_f7d363_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['insurer_name'], name='claims_clai_insurer_b6e0bb_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['status'], name='claims_clai_status_b4f911_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['discharge_date'], name='claims_clai_dischar_7159fd_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['-id'], name='claims_clai_id_a7862d_idx'),
        ),
        migrations.AddIndex(
            model_name='flag',
            index=models.Index(fields=['claim', '-created_at'], name='claims_flag_claim_i_18656c_idx'),
        ),
        migrations.AddIndex(
            model_name='flag',
            index=models.Index(fields=['-created_at'], name='claims_flag_created_d255aa_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['claim', '-created_at'], name='claims_note_claim_i_925552_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['-created_at'], name='claims_note_created_884ec0_idx'),
        ),
    ]
